
export enum GameType {
    CircleProgress = "CircleProgress",
    Progress = "Progress",
    KeyCircle = "KeyCircle",
    KeySpam = "KeySpam",
    NumberSlide = "NumberSlide",
    RapidLines = "RapidLines",
    CircleShake = "CircleShake",
    PathFind = "PathFind",
    Untangle = "Untangle",
    LightsOut = "LightsOut",
    DigitDazzle = "DigitDazzle",
    WordWiz = "WordWiz",
    CircleSum = "CircleSum",
    WaveMatch = "WaveMatch",
    MineSweeper = "MineSweeper",
    PrintLock = "PrintLock",
    HexaPipe = "HexaPipe",
}